import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDir, '..');
const sourceDir = resolve(projectRoot, 'public');
const generatedManifestPath = resolve(projectRoot, 'src/app/gpt-tower/captureAssetManifest.generated.js');
const captureFilePattern = /^capture.*\.json$/i;
const defaultCaptureFile = 'capture.json';

function computeAssetVersion(rawJson) {
    return createHash('sha256').update(rawJson).digest('hex').slice(0, 10);
}

function buildManifestModule(versionByFile) {
    return `// Generated by scripts/prepareRuntimeAssets.mjs
export const LOCAL_CAPTURE_ASSET_VERSION_BY_FILE = Object.freeze(${JSON.stringify(versionByFile, null, 4)});
`;
}

async function loadCaptureAssetVersions() {
    const publicEntries = await readdir(sourceDir, { withFileTypes: true });
    const captureFiles = publicEntries
        .filter((entry) => entry.isFile() && captureFilePattern.test(entry.name))
        .map((entry) => entry.name)
        .sort((left, right) => left.localeCompare(right));

    if (!captureFiles.includes(defaultCaptureFile)) {
        throw new Error(`Expected ${defaultCaptureFile} to exist in public/.`);
    }

    const versionEntries = await Promise.all(captureFiles.map(async (fileName) => {
        const sourcePath = resolve(sourceDir, fileName);
        const rawJson = await readFile(sourcePath, 'utf8');
        JSON.parse(rawJson);
        return [fileName, computeAssetVersion(rawJson)];
    }));

    return Object.fromEntries(versionEntries);
}

async function writeCaptureAssetManifest(versionByFile) {
    const nextContents = buildManifestModule(versionByFile);
    await writeFile(generatedManifestPath, nextContents, 'utf8');
}

async function validateCaptureAsset(fileName) {
    const sourcePath = resolve(sourceDir, fileName);
    const rawJson = await readFile(sourcePath, 'utf8');
    JSON.parse(rawJson);
}

const captureAssetVersions = await loadCaptureAssetVersions();
await Promise.all(Object.keys(captureAssetVersions).map(validateCaptureAsset));
await writeCaptureAssetManifest(captureAssetVersions);
